
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: login
          image: httpd
          ports:
            - containerPort: 80
------------------------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: flip
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: devops
  type: ClusterIP
