apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: login
          image: sakit333/mynotes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---------------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: flip
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 30070
  selector:
    app: devops
  type: NodePort
