apiVersion: v1
kind: ReplicationController
metadata:
  name: umar
spec:
  replicas: 2
  selector:
    app: httpd
  template:
    metadata:
      name: umar1
      labels:
        app: httpd
    spec:
      containers:
        - name: login
          image: httpd
          ports:
            - containerPort: 80
